"""add behavior controls: lock, daily_limit, cooling, pending_transactions

Revision ID: 97afb8f817d6
Revises: c6618f257b26
Create Date: 2026-03-21 04:41:29.734492
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '97afb8f817d6'
down_revision: Union[str, None] = 'c6618f257b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('envelope_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('source', sa.Enum('telegram', 'webapp', name='transactionsource', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'expired', name='pendingtransactionstatus', create_type=True), nullable=False),
    sa.Column('cooling_hours', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirm_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('envelopes', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.add_column('envelopes', sa.Column('daily_limit', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('envelopes', sa.Column('cooling_threshold', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envelopes', 'cooling_threshold')
    op.drop_column('envelopes', 'daily_limit')
    op.drop_column('envelopes', 'is_locked')
    op.drop_table('pending_transactions')
    # ### end Alembic commands ###
