"""add envelope owner_id for personal envelopes

Revision ID: c6618f257b26
Revises: 0f8fa68ae7b7
Create Date: 2026-03-19 05:43:39.981373
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c6618f257b26'
down_revision: Union[str, None] = '0f8fa68ae7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envelopes', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'envelopes', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'envelopes', type_='foreignkey')
    op.drop_column('envelopes', 'owner_id')
    # ### end Alembic commands ###
